bool updated  # to check if the values have been updated or not 

int32 start_hours   #start time begins
int32 start_minutes
int32 start_seconds
int32 start_date
int32 start_month
int32 start_year
int32 end_hours         #end time begins  
int32 end_minutes
int32 end_seconds
int32 end_date
int32 end_month
int32 end_year
float64 lattitude1          #GPS begins geofence
float64 longitude1
float64 lattitude2         
float64 longitude2
float64 allowable_height     # maximum allowable attitude
int32 home_altitude          #refference alitude(in meters)
uint64 timestamp	    #time stamp
